DROP TABLE usuario;
------------ Tabla
CREATE TABLE usuario (
    id_User NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nombre VARCHAR2(15),
    apellido VARCHAR2(15),
    correo VARCHAR2(35),
    telefono VARCHAR(15)
)
------------ Agregar un usuario
CREATE OR REPLACE PROCEDURE addUser(
    in_nombre IN usuario.nombre%TYPE,
    in_apellido IN usuario.apellido%TYPE,
    in_correo IN usuario.correo%TYPE,
    in_telefono IN usuario.telefono%TYPE)
IS
BEGIN
    INSERT INTO usuario (nombre, apellido, correo, telefono)
    VALUES (in_nombre, in_apellido, in_correo, in_telefono);
    COMMIT;
END;
    
------------ Eliminar un usuario
CREATE OR REPLACE PROCEDURE deleteUser (
    p_nombre in usuario.nombre%TYPE,
    p_apellido in usuario.apellido%TYPE) 
IS 
Begin
    Delete from USUARIO WHERE nombre = p_nombre AND apellido = p_apellido; 
    COMMIT; 
END;
------------ Editar un usuario

CREATE OR REPLACE PROCEDURE alterUser (
    ind_nombre IN usuario.nombre%TYPE,
    ind_apellido IN usuario.apellido%TYPE,
    in_nombre IN usuario.nombre%TYPE,
    in_apellido IN usuario.apellido%TYPE,
    in_correo IN usuario.correo%TYPE,
    in_telefono IN usuario.telefono%TYPE)
IS
BEGIN
    UPDATE USUARIO SET nombre = in_nombre, apellido = in_apellido, correo = in_correo, telefono = in_telefono
    WHERE nombre = ind_nombre AND apellido = ind_apellido;
    COMMIT;
END;
